apiVersion: v1
kind: Pod
metadata:
  name: gcloud
  namespace: testns
  labels:
    app: gcloud-cmd
spec:
#  serviceAccountName: ksa
  containers:
  - name: gcloud
    image: image-gcloud # gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]

