# kubectl -n namespace apply -f editor.yaml #  namespace level edit role

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iam-editor
#  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: User
    name: user2@gmail.com
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: user3@gmail.com
    apiGroup: rbac.authorization.k8s.io
