# refer to the link for more sophisticated Cloud SQL: https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqlinstance#mysql_sql_instance_high_availability
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: hil-sql # kpt-set: ${name}
  namespace: tenant-ns # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: tenant-project # kpt-set: ${project-id}
spec:
  databaseVersion: POSTGRES_13
  region: us-central1 # kpt-set: ${region}
  settings:
    tier: db-f1-micro
    ipConfiguration:
      authorizedNetworks:
        - name: allow-all
          value: 0.0.0.0/0

