# https://cloud.google.com/config-connector/docs/reference/resource-docs/resourcemanager/folder#sample_yamls
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: folder-name # kpt-set: blueprints-${name}
  namespace: config-controller-system # kpt-set: ${namespace}
  labels:
    availability: "test"
spec:
  displayName: "folder-name" # kpt-set: blueprints ${name}
  folderRef:
    # Folder ID (can be in a different organization) where service-[PROJECT_NUMBER]@gcp-sa-yakima.iam.gserviceaccount.com
    # needs to have the IAM role binding of Folder Creator, Folder Editor, Project Creator, Project Deleter
    external: "parent-folder-id" # kpt-set: ${parent-folder-id}
