# Use the official Python image at https://hub.docker.com/_/python
FROM python:3.9-slim-bullseye
# IMAGE=us-central1-docker.pkg.dev/$PROJECT_ID/helloworld-docker-repo/hil-promo-dev:0.1 && \
# docker build -f Dockerfile-SA . -t $IMAGE && \
# docker push $IMAGE && \

# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . .
RUN mkdir -p /secrets
COPY firestore-rw.json /secrets/
ENV GOOGLE_APPLICATION_CREDENTIALS=/secrets/firestore-rw.json

# Install cloud run production dependencies.
RUN pip install gunicorn
# install app dependencies
RUN pip install -r requirements.txt

# Ignore /healthz API endpoint for open telemetry
ENV OTEL_PYTHON_FLASK_EXCLUDED_URLS=healthz
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 api:app